### ISSUE TITLE
When selecting the widget to be added to our dashboard, the configure option is disabled. 

### ISSUE THREAD

**Issue by domalbergo** [remarkablemark/jira-dashboard-gadget-issue-formula#400]
## Expected Behavior

When selecting the widget to be added to our dashboard, the configure option is enabled.

## Actual Behavior

When selecting the widget to be added to our dashboard, the configure option is disabled.

## Steps to Reproduce

![image](https://github.com/user-attachments/assets/04d906b7-5c81-4023-b7fb-9f5002c0b33c)

## Reproducible Demo

N/A

## Environment

- Version: 4.0.0
- Platform:
- Browser:
- OS:

## Keywords

gadget,configure,option,disabled

**Comment by remarkablemark** [comment]
@domalbergo can you provide a screenshot? I find it strange that the configure option would be disabled

**Comment by domalbergo** [comment]
Of course! 
<img width="324" alt="Screenshot 2024-09-19 at 9 33 32 AM" src="https://github.com/user-attachments/assets/fd32721e-8fda-4172-b4f5-bc341b2bed85">

**Comment by remarkablemark** [comment]
Thanks @domalbergo. What is the version that you installed?

**Comment by domalbergo** [comment]
Version: 4.0.0

**Comment by domalbergo** [comment]
Yes, I have. This does not resolve the issue.

Dom Albergo
Director, Quality Assurance
LinkedIn | X | Facebook | Instagram

**Comment by remarkablemark** [comment]
Thanks, I was able to reproduce this in a new Jira workspace. I'm going to revert #302 and release:

- https://github.com/remarkablemark/jira-dashboard-gadget-issue-formula/pull/405#issuecomment-2369246005

**Comment by remarkablemark** [comment]
On Atlassian Marketplace, version 4.1.0 still isn't working so I disabled v4 and re-enabled 2.3.0

**Comment by remarkablemark** [comment]
After some troubleshooting, I believe I identified the source of the error:

![Screenshot 2024-09-23 at 5 58 18 PM](https://github.com/user-attachments/assets/7c7576d8-d3b2-4082-8bbe-aad9608ace04)

![Screenshot 2024-09-23 at 5 58 44 PM](https://github.com/user-attachments/assets/b647ef84-8ee8-4f12-86f6-9f3af0da72f2)

**Comment by remarkablemark** [comment]
The bug has been fixed in:

- https://github.com/remarkablemark/jira-dashboard-gadget-issue-formula/pull/411#issuecomment-2369614601

Please update the Jira app to `4.3.0`
